### PR TITLE
Round scores

### LINKED ISSUE #78: Fix formatting of scores
**Describe the bug**
The numerical values of the scores can have multiple decimal places and we should fix this.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by rmcreyes**
# :ship: Pull Request

## :question: Purpose

**Give a brief description of your changes:**
Make scores display with at most 2 decimal places.

## :tickets: Ticket(s)

Closes #78

### CODE REVIEW

File: src/components/Scores.tsx [hunk 1]
```diff
@@ -9,19 +9,22 @@ interface IProps {
 
 export default function Scores(props: IProps) {
     let playerStats: PlayerStats = props.playerStats;
+    let friends: number = Math.round(playerStats.getFriends() * 100) / 100;
```
Comment (eloisepeng) [inline src/components/Scores.tsx]: I thought we can just use `Math.round(playerStats.getFriends(), 2)` to round to 2 digits?

Comment (rmcreyes) [reply src/components/Scores.tsx]: Yeah that looks a bit cleaner
